name: Docker Build and Publish

on:
  release:
    types: [published]
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    name: Slurm ${{ matrix.slurm_version }} / Rocky ${{ matrix.rocky_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - rocky_version: "8"
            slurm_version: "23.02.6"
          - rocky_version: "8"
            slurm_version: "24.11.5"
          - rocky_version: "8"
            slurm_version: "25.05.1"
          - rocky_version: "9"
            slurm_version: "24.11.5"
          - rocky_version: "9"
            slurm_version: "25.05.1"
    steps:
      - name: Check Out Repository Files
        uses: actions/checkout@v3

      - name: Set Up Runner
        uses: './.github/workflows/composite-actions/setup'

      - name: Set Version Overrides
        run: |
          echo "SLURM_VERSION=${{ matrix.slurm_version }}" >> $GITHUB_ENV
          echo "CONTAINER_ROCKY_VERSION=${{ matrix.rocky_version }}" >> $GITHUB_ENV
          SLURM_SHORT=$(echo "${{ matrix.slurm_version }}" | cut -d. -f1,2)
          echo "SLURM_VERSION_SHORT=${SLURM_SHORT}" >> $GITHUB_ENV

      - name: Set Image Tags
        id: tags
        run: |
          sv="${SLURM_VERSION_SHORT}"
          el="el${{ matrix.rocky_version }}"
          suffix="${sv}-${el}"
          if [[ "${{ github.event_name}}" == "release" ]]; then
            suffix="${suffix}-${{ github.ref_name }}"
          fi
          echo "TAG_BASE_STANDARD=${{ env.TAG_BASE_STANDARD }}-${suffix}" >> $GITHUB_OUTPUT
          echo "TAG_BASE_ROOT=${{ env.TAG_BASE_ROOT }}-${suffix}" >> $GITHUB_OUTPUT
          echo "TAG_FULL_STANDARD=${{ env.TAG_FULL_STANDARD }}-${suffix}" >> $GITHUB_OUTPUT
          echo "TAG_FULL_ROOT=${{ env.TAG_FULL_ROOT }}-${suffix}" >> $GITHUB_OUTPUT

      - name: Publish Docker Image - base - standard
        if: ${{ always() }}
        uses: './.github/workflows/composite-actions/test-publish'
        with:
          user: standard
          docker_build_context: dockerfile_base/
          publish_repo: ${{ env.DOCKER_HUB_REPO }}
          publish_tag: ${{ steps.tags.outputs.TAG_BASE_STANDARD }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish Docker Image - base - root
        if: ${{ always() }}
        uses: './.github/workflows/composite-actions/test-publish'
        with:
          user: root
          docker_build_context: dockerfile_base/
          publish_repo: ${{ env.DOCKER_HUB_REPO }}
          publish_tag: ${{ steps.tags.outputs.TAG_BASE_ROOT }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set BASE_TAG for Full Image Dependency
        run: |
          sv="${SLURM_VERSION_SHORT}"
          el="el${{ matrix.rocky_version }}"
          echo "TAG_BASE_ROOT=${{ env.TAG_BASE_ROOT }}-${sv}-${el}" >> $GITHUB_ENV

      - name: Build Image - base/root (full image dependency)
        uses: './.github/workflows/composite-actions/docker-build-push'
        with:
          user: root
          context: dockerfile_base/
          load: 'true'
          push: 'false'
          tags: ${{ env.DOCKER_HUB_REPO }}:${{ env.TAG_BASE_ROOT }}

      - name: Publish Docker Image - full - standard
        if: ${{ always() }}
        uses: './.github/workflows/composite-actions/test-publish'
        with:
          user: standard
          docker_build_context: dockerfile_full/
          publish_repo: ${{ env.DOCKER_HUB_REPO }}
          publish_tag: ${{ steps.tags.outputs.TAG_FULL_STANDARD }}
          required_images: ${{ env.DOCKER_HUB_REPO }}:${{ env.TAG_BASE_ROOT }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish Docker Image - full - root
        if: ${{ always() }}
        uses: './.github/workflows/composite-actions/test-publish'
        with:
          user: root
          docker_build_context: dockerfile_full/
          publish_repo: ${{ env.DOCKER_HUB_REPO }}
          publish_tag: ${{ steps.tags.outputs.TAG_FULL_ROOT }}
          required_images: ${{ env.DOCKER_HUB_REPO }}:${{ env.TAG_BASE_ROOT }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
