name: Pre-commit Checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check Out Repository Files
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
